export const weathers = [
    {
        id:0,
        name:'晴天',
        icon:'assets/weathers/sunny.ico'
    },
    {
        id:1,
        name:'多云',
        icon:'assets/weathers/cloudy.ico'
    },
    {
        id:2,
        name:'阴天',
        icon:'assets/weathers/overcast.ico'
    },
    {
        id:3,
        name:'有雾',
        icon:'assets/weathers/smog.ico'
    },
    {
        id:4,
        name:'下雨',
        icon:'assets/weathers/rainy.ico'
    },
    {
        id:5,
        name:'雷雨',
        icon:'assets/weathers/thunder.ico'
    },
    {
        id:6,
        name:'下雪',
        icon:'assets/weathers/snowy.ico'
    },
    {
        id:7,
        name:'有风',
        icon:'assets/weathers/windy.ico'
    },
]